/* banco de dados */
CREATE DATABASE BDCADASTROCLIENTE

    USE BDCADASTROCLIENTE

    CREATE TABLE CLIENTE (
    ID INT NOT NULL IDENTITY,
    NOME VARCHAR(50) NOT NULL,
    ENDEREÇO VARCHAR(50),
    CEP VARCHAR (50),
    BAIRRO VARCHAR (50),
    CIDADE VARCHAR (50),
    UF VARCHAR (2),
    TELEFONE VARCHAR(15),
    EMAIL VARCHAR (50),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
    )